name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Test on ${{ matrix.os }} (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.9"
            toxenv: py39-linux
          - os: macos-latest
            python-version: "3.9"
            toxenv: py39-macos
          - os: windows-latest
            python-version: "3.9"
            toxenv: py39-windows
          - os: ubuntu-latest
            python-version: "3.12"
            toxenv: py312-linux
          - os: macos-latest
            python-version: "3.12"
            toxenv: py312-macos
          - os: windows-latest
            python-version: "3.12"
            toxenv: py312-windows

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package and tox
      run: |
        python -m pip install --upgrade pip --no-cache-dir
        pip install -e . --no-cache-dir
        pip install --no-cache-dir tox

    - name: Run tests with tox
      run: tox -e ${{ matrix.toxenv }}

  deploy:
    name: Deploy Package
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip --no-cache-dir
        pip install --no-cache-dir build twine setuptools setuptools_scm wheel

    - name: Build distribution
      run: python -m build --sdist --wheel

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
      run: python -m twine upload dist/*
